
dataset:
  root: "file:D:/data/sign-languages/lsfb-cont"
  train_shards_url: "shards/shard_{000000..000003}.tar"
  val_shards_url: "shards/shard_000004.tar"
  test_shards_url: "shards/shard_000004.tar"

preprocessing:
  use_windows: true
  window_size: 3500
  window_stride: 2800
  transforms_pipeline: "norm+flatten-pose"

backbone:
  name: 'mstcn'
  multilayer_output: true
  checkpoint_path: "D:/data/sign-languages/outs/sls/alpha1/checkpoints/lsfb_io_off_244841/epoch=79-step=24320.ckpt"
  args:
    in_channels: 130
    hidden_channels: 64
    n_stages: 4
    n_layers: 10
    # 2 for classification, and 2 for offsets
    out_channels: 4

target:
  offsets: true
  encoder:
    name: 'offsets+actionness'
    args: {}
  decoder:
    name: 'offsets+actionness'
    args:
      n_classes: 2
      soft_nms_method: 'gaussian'
      soft_nms_sigma: 0.1
      soft_nms_threshold: 0.5

training:
  batch_size: 8
  n_workers: 0
  criterion: 'multi-layer+ce+smoothing+offsets'
  learning_rate: 2e-4
  n_epochs: 200
  gradient_clipping: 0.0
  early_stopping_patience: 10
  criterion_use_weights: false
  skip_training: true
  skip_testing: false

experiment:
  name: "lsfb_io_off"
  debug: true
  out_dir: "D:/data/sign-languages/outs/sls/alpha2"