dataset:
  root: "/gpfs/scratch/acad/lsfb/datasets/dgs_corpus"
  train_shards_url: "shards/shard_{000000..000002}.tar"
  val_shards_url: "shards/shard_000003.tar"
  test_shards_url: "shards/shard_000004.tar"

preprocessing:
  use_windows: true
  window_size: 1500
  window_stride: 1200
  transforms_pipeline: 'optical-flow'

target:
  type: "actionness"
  boundary_noise: 0

training:
  batch_size: 8
  n_workers: 1
  criterion: 'ce'
  learning_rate: 1e-3
  n_epochs: 100
  gradient_clipping: 0.5

backbone:
  name: 'rnn'
  args:
    in_channels: 65
    hidden_channels: 256
    n_layers: 2
    out_channels: 2
    bidirectional: true
    rnn: 'lstm'

experiment:
  name: "dgs_o_lstm_h256_2l_io"
  debug: false
  out_dir: "/gpfs/scratch/acad/lsfb/out/dgs"