from: 'example.yaml'

dataset:
  root: "/gpfs/scratch/acad/lsfb/datasets/dgs_corpus"
  train_shards_url: "shards/shard_{000000..000002}.tar"
  val_shards_url: "shards/shard_000003.tar"
  test_shards_url: "shards/shard_000004.tar"

training:
  batch_size: 8
  n_workers: 1
  criterion: 'ce'

backbone:
  name: 'rnn'
  args:
    in_channels: 65
    hidden_channels: 64
    out_channels: 3
    bidirectional: true
    rnn: 'lstm'

experiment:
  name: "dgs_rep"
  debug: false
  out_dir: "/gpfs/scratch/acad/lsfb/out/dgs"

target:
  type: "bio_tags"
  boundary_noise: 0