
dataset:
  root: "file:D:/data/sign-languages/dgs-corpus"
  train_shards_url: "shards/shard_{000000..000002}.tar"
  val_shards_url: "shards/shard_000003.tar"
  test_shards_url: "shards/shard_000004.tar"

preprocessing:
  use_windows: true
  window_size: 1500
  window_stride: 1200
  transforms_pipeline: 'optical-flow'

backbone:
  name: 'rnn'
  args:
    in_channels: 65
    hidden_channels: 64
    out_channels: 3
    bidirectional: true
    rnn: 'lstm'

target:
  offsets: false
  encoder:
    name: 'bio_tags'
    args: {}
  decoder:
    name: 'bio_tags'
    args: {}

training:
  batch_size: 2
  n_workers: 0
  criterion: 'ce'
  criterion_use_weights: false
  learning_rate: 1e-3
  n_epochs: 100
  gradient_clipping: 0.5
  early_stopping_patience: 10
  skip_training: false
  skip_testing: true

experiment:
  name: "segmentation"
  debug: true
  out_dir: "./out"
