from: "dgs_o_mstcn_h64_4s_6l_io.yaml"

preprocessing:
  transforms_pipeline: "norm+flatten-pose||norm+optical-flow"

backbone:
  args:
    in_channels: 195

experiment:
  name: "dgs_opn_mstcn_h64_4s_6l_io"