from: "dgs_o_mstcn_h64_4s_6l_io.yaml"

backbone:
  args:
    out_channels: 3

target:
  offsets: false
  encoder:
    name: 'bio_tags'
    args: {}
  decoder:
    name: 'bio_tags'
    args: {}

experiment:
  name: "dgs_o_mstcn_h64_4s_6l_bio"
