
dataset:
  root: "/gpfs/scratch/acad/lsfb/datasets/dgs_corpus"
  train_shards_url: "shards/shard_{000000..000002}.tar"
  val_shards_url: "shards/shard_000003.tar"
  test_shards_url: "shards/shard_000004.tar"

preprocessing:
  use_windows: true
  window_size: 3500
  window_stride: 2800
  transforms_pipeline: 'optical-flow'

backbone:
  name: 'rnn'
  multilayer_output: false
  args:
    in_channels: 65
    hidden_channels: 64
    n_layers: 1
    out_channels: 2
    bidirectional: true
    rnn: 'lstm'

target:
  offsets: false
  encoder:
    name: 'actionness'
    args: {}
  decoder:
    name: 'actionness'
    args: {}

training:
  batch_size: 8
  n_workers: 1
  criterion: 'ce'
  learning_rate: 2e-4
  n_epochs: 200
  gradient_clipping: 0.5
  early_stopping_patience: 10
  criterion_use_weights: false
  skip_training: false
  skip_testing: false

experiment:
  name: "dgs_o_lstm_h64_1l_io"
  debug: false
  out_dir: "/gpfs/scratch/acad/lsfb/out/dgs/exp_archs"