
dataset:
  root: "/run/media/ppoitier/ppoitier/datasets/sign-languages/dgs_corpus"
  train_shards_url: "shards/shard_{000000..000002}.tar"
  val_shards_url: "shards/shard_000003.tar"
  test_shards_url: "shards/shard_000004.tar"

preprocessing:
  use_windows: true
  window_size: 1500
  window_stride: 1200
  transforms_pipeline: 'optical-flow'

backbone:
  name: 'mstcn'
  multilayer_output: true
  checkpoint_path: "/run/media/ppoitier/ppoitier/output/sls/offsets/checkpoints/dgs_o_mstcn_h64_io_off_22706/epoch=44-step=47925.ckpt"
  args:
    in_channels: 65
    hidden_channels: 64
    n_stages: 4
    n_layers: 6
    # 2 for classification, and 2 for offsets
    out_channels: 4

target:
  offsets: true
  encoder:
    name: 'offsets+actionness'
    args: {}
  decoder:
    name: 'offsets+actionness'
    args:
      soft_nms_method: 'gaussian'
      soft_nms_sigma: 0.1
      soft_nms_threshold: 0.2

training:
  batch_size: 8
  n_workers: 7
  criterion: 'offsets+actionness'
  learning_rate: 1e-3
  n_epochs: 150
  gradient_clipping: 0.0
  early_stopping_patience: 5
  criterion_use_weights: false
  skip_training: true
  skip_testing: false

experiment:
  name: "dgs_o_mstcn_h64_io_off"
  debug: false
  out_dir: "/run/media/ppoitier/ppoitier/output/sls/offsets"