
dataset:
  root: "/gpfs/scratch/acad/lsfb/datasets/dgs_corpus"
  train_shards_url: "shards/shard_{000000..000002}.tar"
  val_shards_url: "shards/shard_000003.tar"
  test_shards_url: "shards/shard_000004.tar"

preprocessing:
  use_windows: true
  window_size: 1500
  window_stride: 1200
  transforms_pipeline: 'optical-flow'

backbone:
  name: 'mstcn'
  args:
    in_channels: 65
    hidden_channels: 64
    n_stages: 4
    n_layers: 6
    out_channels: 2

target:
  offsets: false
  encoder:
    name: 'actionness'
    args: {}
  decoder:
    name: 'actionness'
    args: {}

training:
  batch_size: 8
  n_workers: 1
  criterion: 'mstcn'
  learning_rate: 1e-3
  n_epochs: 150
  gradient_clipping: 0.0
  early_stopping_patience: 5
  criterion_use_weights: false
  skip_training: false
  skip_testing: false

experiment:
  name: "w1500_dgs_o_mstcn_h64_io"
  debug: false
  out_dir: "/gpfs/scratch/acad/lsfb/out/dgs/exp_windows"