from: "dgs_io.yaml"

dataset:
  root: "/gpfs/scratch/acad/lsfb/datasets/bobsl"
  train_shards_url: "shards/shard_{000000..000001}.tar"
  val_shards_url: "shards/shard_000002.tar"
  test_shards_url: "shards/shard_000002.tar"

experiment:
  name: "bobsl_io"
